language: python
python: "2.7"
dist: trusty

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Bring pip up to date 
  - pip install --upgrade pip setuptools wheel
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git

install:
  - python ./setup.py install
  - pip install -r requirements-test.txt
  - pip install python-coveralls
  - pip install spinnaker_proxy

script:
  - py.test . --cov spinnman
  # Code quality check
  - flake8 spinnman unittests
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
