# Copyright (c) 2020 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Actions
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            python-version: "3.13"
            checks: 'full'

          - runner: ubuntu-latest
            python-version: "3.12"
            checks: 'validate'

          - runner: ubuntu-latest
            python-version: "3.11"
            checks: 'full'
            coverage: 'coverage'

          - runner: ubuntu-latest
            python-version: "3.10"
            checks: 'full'

          - runner: ubuntu-22.04
            python-version: 3.9
            checks: 'full'

          - runner: ubuntu-20.04
            python-version: 3.8
            checks: 'full'

          - runner: windows-latest
            python-version: "3.12"
            checks: 'tests'

          - runner: windows-2019
            python-version: 3.8
            checks: 'tests'

          - runner: macos-latest
            python-version: "3.12"
            checks: 'tests'

          - runner: macos-11
            python-version: 3.8
            checks: 'tests'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout SupportScripts
      uses: actions/checkout@v4
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support

    - name: Preparation actions
      uses: ./support/actions/prepare
      with:
        python-version: ${{ matrix.python-version }}
        dependencies: SpiNNUtils SpiNNMachine
        install: true

    - name: Validation actions
      if: {{ matrix.checks == 'validate' }}
      uses: ./support/actions/validate

    - name: Unittests and style checks
      if: ${{ matrix.checks == 'full' || matrix.checks == 'validate' }}
      uses: ./support/actions/test-and-check
      with:
        python-version: ${{ matrix.python-version }}
        tests: unittests
        cover-packages: spinnman
        coveralls-token: ${{ secrets.GITHUB_TOKEN }}
        flake8_packages: spinnman unittests
        pylint_package: spinnman unittests

    - name: Simple pytest
      if: ${{ matrix.checks == 'tests'}}
      env:
        SPALLOC_USER: ${{ secrets.SPALLOC_USER }}
        SPALLOC_PASSWORD: ${{ secrets.SPALLOC_PASSWORD }}
      run: | 
        pytest unittests
        pytest spinnman_integration_tests
